blank_issues_enabled: true
contact_links:
  - name: Car Thing Community Discussions
    url: https://github.com/Gilzone/carthing-apps/discussions
    about: Ask questions and discuss with other Car Thing enthusiasts
